[Details]
  Icon = "Icon.png"
  Name = "crocgui"
  ID = "com.github.howeyc.crocgui"
  Version = "1.11.5"
  Build = 15

[LinuxAndBSD]
  GenericName = "GUI for croc"
  Categories = ["FileTransfer"]
  Comment = "A nice simple GUI for croc"
